########################################
# General Vars
########################################

variable "name" {
  default     = "mysql-postgres"
  description = "common name for resources in this module"
  type        = string
}

variable "tags" {
  default     = {}
  description = "Tags to apply to supported resources"
  type        = map(string)
}

########################################
# Access Control Vars
########################################

variable "allowed_cidr_blocks" {
  default     = []
  description = "CIDR blocks allowed to reach the database"
  type        = list(string)
}

variable "allowed_ipv6_cidr_blocks" {
  default     = []
  description = "IPv6 CIDR blocks allowed to reach the database"
  type        = list(string)
}

variable "allowed_security_groups" {
  default     = []
  description = "IDs of security groups allowed to reach the database (not Names)"
  type        = list(string)
}

########################################
# DB Authentication Vars
########################################

variable "create_secretmanager_secret" {
  default     = true
  description = "True to create a secretmanager secret containing DB password (not used if `password` is set)"
  type        = bool
}

variable "create_ssm_secret" {
  default     = false
  description = "True to create a SSM Parameter SecretString containing DB password (not used if `password` is set)"
  type        = bool
}

variable "password" {
  default     = null
  description = "Master password (if not set, one will be generated dynamically)"
  type        = string
}

variable "password_length" {
  default     = 30
  description = "Master password length (not used if `password` is set)"
  type        = number
}

variable "pass_version" {
  default     = 1
  description = "Increment to force master user password change (not used if `password` is set)"
  type        = number
}

variable "ssm_path" {
  default     = ""
  description = "Custom path for SSM parameter, only takes effect if `create_ssm_secret` is true. "
  type        = string
}

########################################
# Database Config Vars
########################################

variable "backup_retention_period" {
  default     = 5
  description = "How long to keep RDS backups (in days)"
  type        = string
}

variable "cloudwatch_log_exports" {
  description = "Log types to export to CloudWatch"
  type        = list(string)

  default = [
    "postgresql",
    "upgrade"
  ]
}

variable "database_name" {
  default     = null
  description = "Name of the initial database to create. (null for none)"
  type        = string
}

variable "enable_deletion_protection" {
  default     = true
  description = "If `true`, deletion protection will be turned on for the RDS instance(s)"
  type        = bool
}

variable "engine_version" {
  default     = "11.5"
  description = "Version of database engine to use"
  type        = string
}

variable "final_snapshot_identifier" {
  default     = null
  description = "name of final snapshot (will be computed automatically if not specified)"
  type        = string
}

variable "iam_database_authentication_enabled" {
  default     = false
  description = "True to enable IAM DB authentication"
  type        = bool
}

variable "ignore_engine_version_change" {
  default     = true
  description = "Ignore changes to the `var.engine_version` caused by automatic upgrades"
  type        = bool
}

variable "parameters" {
  description = "Database parameters (will create parameter group if not null)"

  default = [
    {
      apply_method = "immediate"
      name         = "client_encoding"
      value        = "UTF8"
    }
  ]

  type = list(object({
    apply_method = string
    name         = string
    value        = string
  }))
}

variable "parameter_group_family" {
  default     = ""
  description = "Parameter Group Family. Need to make explicit for Postgres 9.x"
  type        = string
}

variable "performance_insights_enabled" {
  default     = false
  description = "If true, performance insights will be enabled"
  type        = bool
}

variable "skip_final_snapshot" {
  default     = false
  description = "If true no final snapshot will be taken on termination"
  type        = bool
}

variable "username" {
  default     = "postgres"
  description = "Username of master user"
  type        = string
}

########################################
# Instance Vars
########################################

variable "identifier" {
  default     = null
  description = "DB identifier (not recommended, only used if `identifier_prefix` is not null)"
  type        = string
}

variable "identifier_prefix" {
  default     = null
  description = "DB identifier prefix (will be generated by AWS automatically if not specified)"
  type        = string
}

variable "instance_class" {
  description = "What instance type to use"
  type        = string
}

variable "monitoring_interval" {
  default     = 0
  description = "Monitoring interval in seconds (`0` to disable enhanced monitoring)"
  type        = number
}

variable "monitoring_role_arn" {
  default     = null
  description = "Enhanced Monitoring ARN (if `monitoring_interval > 0` and this is omitted, a role will be created automatically)"
  type        = string
}

variable "multi_az" {
  default     = true
  description = "whether to make database multi-az"
  type        = bool
}

variable "storage" {
  default     = 20
  description = "How much storage is available to the database"
  type        = string
}

variable "storage_encrypted" {
  default     = true
  description = "Encrypt DB storage"
  type        = bool
}

variable "storage_type" {
  default     = "gp2"
  description = "What storage backend to use (`gp2` or `standard`. io1 not supported)"
  type        = string
}

########################################
# Networking Vars
########################################

variable "port" {
  default     = 5432
  description = "Port the database should listen on"
  type        = number
}

variable "subnet_group_name" {
  description = "name of DB subnet group to place DB in"
  type        = string
}

variable "vpc_id" {
  description = "ID of VPC resources will be created in"
  type        = string
}
